// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwWzUtu23m1MwJXvIeb3uoVTUm-gpu5L4',
    appId: '1:991057166521:web:c49441e7a783d82452db68',
    messagingSenderId: '991057166521',
    projectId: 'vita-924ac',
    authDomain: 'vita-924ac.firebaseapp.com',
    storageBucket: 'vita-924ac.firebasestorage.app',
    measurementId: 'G-2JVHNR8SVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzHCw8yYQNU_2leoNQMOOycRA-diDOq-c',
    appId: '1:991057166521:android:cceb9584ebc7c95152db68',
    messagingSenderId: '991057166521',
    projectId: 'vita-924ac',
    storageBucket: 'vita-924ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpA8B46YaExhih-RmFwuGrXgCwqBbPvUQ',
    appId: '1:991057166521:ios:dd717422ee37db1752db68',
    messagingSenderId: '991057166521',
    projectId: 'vita-924ac',
    storageBucket: 'vita-924ac.firebasestorage.app',
    iosBundleId: 'com.example.vitapsyche',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpA8B46YaExhih-RmFwuGrXgCwqBbPvUQ',
    appId: '1:991057166521:ios:dd717422ee37db1752db68',
    messagingSenderId: '991057166521',
    projectId: 'vita-924ac',
    storageBucket: 'vita-924ac.firebasestorage.app',
    iosBundleId: 'com.example.vitapsyche',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwWzUtu23m1MwJXvIeb3uoVTUm-gpu5L4',
    appId: '1:991057166521:web:8549ccba6a2a1ef652db68',
    messagingSenderId: '991057166521',
    projectId: 'vita-924ac',
    authDomain: 'vita-924ac.firebaseapp.com',
    storageBucket: 'vita-924ac.firebasestorage.app',
    measurementId: 'G-VCJ503D8NG',
  );
}
